version: '2'

services:
  # zookeeper:
  #   image: docker.io/bitnami/zookeeper:3.7
  #   ports:
  #     - '2181:2181'
  #   volumes:
  #     - 'zookeeper_data:/bitnami'
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #   networks:
  #     - app-tier
  # kafka:
  #   image: docker.io/bitnami/kafka:2
  #   ports:
  #     - '9093:9093'
  #   volumes:
  #     - 'kafka_data:/bitnami'
  #   environment:
  #     - KAFKA_ADVERTISED_HOST_NAME=kafka
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
  #     - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
  #   depends_on:
  #     - zookeeper
  #   networks:
  #     - app-tier
  # server:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     PORT: 3000
  #     KAFKA_BROKERS: kafka:9092
  #   depends_on:
  #     - kafka
  #   networks:
  #     - app-tier
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app-tier
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - 5601:5601
    depends_on:
      - es01
    networks:
      - app-tier
    

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  esdata1:
    driver: local

networks:
  app-tier:
    driver: bridge